let mapleader = ","
let g:mapleader = ","

"----------------------------------------------------------------------------------------------
"switch between this.that and this->that
let g:switch_mapping = "<Leader>,"
let b:switch_custom_definitions = [
            \   {
            \     '\(\k\+\)\.': '\1->',
            \     '\(\k\+\)->': '\1.',
            \    }
            \ ]

"CamelCase Motion settings
" shift-w, shift-b, shift-e
" to move by camelCase word
map <S-W> <Plug>CamelCaseMotion_w
map <S-B> <Plug>CamelCaseMotion_b
map <S-E> <Plug>CamelCaseMotion_e


"Default to CamelCase Motion settings
"try this out and see if I like it
" map <silent> w <Plug>CamelCaseMotion_w
" map <silent> b <Plug>CamelCaseMotion_b
" map <silent> e <Plug>CamelCaseMotion_e
" map <silent> ge <Plug>CamelCaseMotion_ge
" sunmap w
" sunmap b
" sunmap e
" sunmap ge

function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~# '\s'
endfunction

"TODO maybe integrate into plugin
let g:skeleton_replacements = {}
function! g:skeleton_replacements.UBASENAME()
    return toupper(fnamemodify(expand('%'), ':t:r'))
endfunction

let g:netrw_dirhistmax = 0 " disable netrw history file
let g:netrw_winsize = 20 " default width size in characters
let g:netrw_liststyle = 3 " tree style file view
" comma e to toggle explorer
nnoremap <Leader>e :Lexplore<CR>

filetype plugin indent on
set nocompatible
set smartindent
set tabstop=8
set shiftwidth=4
set softtabstop=4
set expandtab
set wrap
set scrolloff=5
autocmd BufNewFile,BufNew,BufRead TODO,*.md,*.html,*.css,*.js,*.vue,*.rb,*.html.erb set shiftwidth=2 softtabstop=2

"File specific settings
autocmd BufNewFile,BufRead *.rs set filetype=rust

autocmd BufNewFile,BufNew,BufRead *.c set colorcolumn=80
autocmd FileType c,cpp setlocal equalprg=clang-format
autocmd FileType cpp setlocal keywordprg=cppman
autocmd FileType py setlocal keywordprg=pydoc

set mouse=a
set mousemodel=popup_setpos " for ale popup

set wildmenu
set nocursorline "decreases latency on large files

"set spell
set spelloptions=camel " spell check on camel case too
set spellcapcheck= " disable capitalization error on first letter of string

syntax on
set nojoinspaces
set number
"set relativenumber

set encoding=utf-8
set laststatus=2

" Custom mappings
nnoremap  ; :
inoremap jk <esc>
inoremap kj <esc>

"Change the keys for scrolling the entire screen
nnoremap <space> <C-d>
nnoremap <backspace> <C-u>

"Use minus to jump to end of line.
nnoremap - $
onoremap - $

"change line wrap down cursor behavior
nnoremap j gj
nnoremap k gk

"fix common typo
cnoremap q1 q!

"Ctags settings
set tags=./tags,tags,~/.vim/ctags/tags,.git/tags

"XDG_STATE_HOME viminfo
" set viminfofile=~/.local/state/vim/viminfo

if has("xterm_clipboard")
    set clipboard=unnamedplus
endif

" styling
set bg=dark " manually set background color to dark; not automatically detected in tmux
colorscheme collin

" install with debian for more stable version
" sudo apt-get install vim-ale
let g:ale_linters = {'rust': ['analyzer']}
packadd! ale
autocmd FileType rust source /home/collin/.dotfiles/vim/rust.vim

" config that applies to just this file
" :h modeline
" vim: nospell
