let mapleader = ","
let g:mapleader = ","

"----------------------------------------------------------------------------------------------
"switch between this.that and this->that
let g:switch_mapping = "<Leader>,"
let b:switch_custom_definitions = [
            \   {
            \     '\(\k\+\)\.': '\1->',
            \     '\(\k\+\)->': '\1.',
            \    }
            \ ]

"CamelCase Motion settings
" shift-w, shift-b, shift-e
" to move by camelCase word
map <S-W> <Plug>CamelCaseMotion_w
map <S-B> <Plug>CamelCaseMotion_b
map <S-E> <Plug>CamelCaseMotion_e

function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~# '\s'
endfunction

"TODO maybe integrate into plugin
let g:skeleton_replacements = {}
function! g:skeleton_replacements.UBASENAME()
    return toupper(fnamemodify(expand('%'), ':t:r'))
endfunction

let g:netrw_dirhistmax = 0 " disable netrw history file
let g:netrw_winsize = 20 " default width size in characters
let g:netrw_liststyle = 3 " tree style file view
" comma e to toggle explorer
nnoremap <Leader>e :Lexplore<CR>

filetype plugin indent on
set nocompatible
set smartindent
set tabstop=8
set shiftwidth=4
set softtabstop=4
set expandtab
set wrap
autocmd BufNewFile,BufNew,BufRead TODO,*.md,*.html,*.css,*.js,*.vue,*.rb,*.html.erb set shiftwidth=2 softtabstop=2

"File specific settings
autocmd BufNewFile,BufRead *.rs set filetype=rust

autocmd BufNewFile,BufNew,BufRead *.c set colorcolumn=80
autocmd FileType c,cpp setlocal equalprg=clang-format
autocmd FileType rust setlocal equalprg=rustfmt
autocmd FileType cpp setlocal keywordprg=cppman
autocmd FileType py setlocal keywordprg=pydoc

set mouse=a
set mousemodel=popup_setpos " for ale popup

set wildmenu
set nocursorline "decreases latency on large files

"set spell
set spelloptions=camel " spell check on camel case too
set spellcapcheck= " disable capitalization error on first letter of string

syntax on
set nojoinspaces
set nowrap
set number
"set relativenumber

set encoding=utf-8
set laststatus=2

"
" Custom mappings
nnoremap  ; :
inoremap jk <esc>
inoremap kj <esc>

"Change the keys for scrolling the entire screen
nnoremap <space> <C-d>
nnoremap <backspace> <C-u>

"Use minus to jump to end of line.
nnoremap - $
onoremap - $

"change line wrap down cursor behavior
nnoremap j gj
nnoremap k gk

"fix common typo
cnoremap q1 q!

"Ctags settings
set tags=./tags,tags,~/.vim/ctags/tags,.git/tags

"XDG_STATE_HOME viminfo
set viminfofile=~/.local/state/vim/viminfo

if has("xterm_clipboard")
    set clipboard=unnamedplus
endif

" set completeopt=menu,menuone,preview,noselect,noinsert
set completeopt=menu,menuone,popup,noselect,noinsert

set omnifunc=ale#completion#OmniFunc
let g:ale_enabled = 1
let g:ale_completion_enabled = 1

" displat rust information in floating window
let g:ale_floating_preview = 1
let g:ale_floating_window_border = repeat([''], 8)

let g:ale_linters_explicit = 1
let g:ale_fixers_explicit = 1
let g:rustfmt_autosave = 1
let g:ale_linters = { 'rust': ['analyzer'] }
let b:ale_fixers = {'rust': ['rustfmt', 'trim_whitespace', 'remove_trailing_lines']}

" K for popup rust docs
autocmd FileType rust nnoremap K :ALEHover<CR>
" ctrl ] to jump to implementation
autocmd FileType rust nnoremap <C-]> :ALEGoToDefinition<CR>
" ctrl click to jump to implementation
autocmd FileType rust nnoremap <C-LeftMouse> :ALEGoToDefinition<CR>
" leader f for quick fix
autocmd FileType rust nnoremap <Leader>f :ALECodeAction<CR>

" ctrl shift i to reformat file like vscode
autocmd FileType rust inoremap <C-I> <ESC>mZHmY:%!rustfmt<CR>'Yzt`Z
autocmd FileType rust nnoremap <C-I> mZHmY:%!rustfmt<CR>'Yzt`Z

" config that applies to just this file
" :h modeline
" vim: nospell
