set-option global ui_options terminal_assistant=none

add-highlighter global/ number-lines -hlcursor
add-highlighter global/ show-matching

map global normal 0 "gh"
map global normal <minus> "gl"

eval %sh{kak-lsp --kakoune -s $kak_session}  # Not needed if you load it with plug.kak.
lsp-enable

lsp-auto-hover-enable
