# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# add_newline = false
battery.disabled = true

format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$c\
$python\
$rust\
$buf\
$memory_usage\
$direnv\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$time\
$status\
$os\
$container\
$shell\
$character"""
