#!/bin/bash

function mklink() {
    dst="$1"
    src="$2"
    ln -s "$dst" "$src"
}

source ../bash/environments
mklink $DOTFILES_DIR/bash $HOME/.config
mklink $DOTFILES_DIR/git $HOME/.config
mklink $DOTFILES_DIR/npm $HOME/.config
mklink $DOTFILES_DIR/tmux $HOME/.config

echo updating vim plugins
~/.vim/install.sh ~/.vim # install vim plugins
