#!/bin/bash

function mklink() {
    dst="$1"
    src="$2"

    if [ -e "${src}/$(basename $dst)" ];then
        echo dest "${src}/$(basename $dst)" already exists
    else
        ln -s "$dst" "$src"
    fi
}

source ../bash/environments
mklink $DOTFILES_DIR/bash $HOME/.config
mklink $DOTFILES_DIR/git $HOME/.config
mklink $DOTFILES_DIR/npm $HOME/.config
mklink $DOTFILES_DIR/tmux $HOME/.config

~/.vim/install.sh ~/.vim # install vim plugins
