#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -v -g
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $MKDIR -p "$($DIRNAME "$2")"
  $LN -sf "$1" "$2"
}
handle_file_ln "$HOME/.dotfiles/tag-bash/aliases" "$HOME/.aliases"
handle_file_ln "$HOME/.dotfiles/tag-bash/bashrc" "$HOME/.bashrc"
handle_file_ln "$HOME/.dotfiles/tag-bash/dircolors" "$HOME/.dircolors"
handle_file_ln "$HOME/.dotfiles/tag-bash/inputrc" "$HOME/.inputrc"
handle_file_ln "$HOME/.dotfiles/tag-git/gitconfig" "$HOME/.gitconfig"
handle_file_ln "$HOME/.dotfiles/tag-git/gituserinfo" "$HOME/.gituserinfo"
handle_file_ln "$HOME/.dotfiles/tag-vim/vim/ctags/gen-tags" "$HOME/.vim/ctags/gen-tags"
handle_file_ln "$HOME/.dotfiles/tag-vim/vim/templates/skel.c" "$HOME/.vim/templates/skel.c"
handle_file_ln "$HOME/.dotfiles/tag-vim/vim/templates/skel.h" "$HOME/.vim/templates/skel.h"
handle_file_ln "$HOME/.dotfiles/tag-vim/vim/templates/skel.html" "$HOME/.vim/templates/skel.html"
handle_file_ln "$HOME/.dotfiles/tag-vim/vim/templates/skel.java" "$HOME/.vim/templates/skel.java"
handle_file_ln "$HOME/.dotfiles/tag-vim/vim/templates/skel.rs" "$HOME/.vim/templates/skel.rs"
handle_file_ln "$HOME/.dotfiles/tag-vim/vim/templates/skel.tex" "$HOME/.vim/templates/skel.tex"
handle_file_ln "$HOME/.dotfiles/tag-vim/vim/templates/skel.xml" "$HOME/.vim/templates/skel.xml"
handle_file_ln "$HOME/.dotfiles/tag-vim/vimrc" "$HOME/.vimrc"
handle_file_ln "$HOME/.dotfiles/agignore" "$HOME/.agignore"
handle_file_ln "$HOME/.dotfiles/rcrc" "$HOME/.rcrc"
handle_file_ln "$HOME/.dotfiles/tmux.conf" "$HOME/.tmux.conf"
